from flask import Flask, request, render_template
from dotenv import load_dotenv 
import os , pymongo

load_dotenv()
Mongo_uri = os.getenv('Mongo_uri')
client = pymongo.MongoClient( Mongo_uri )
db = client.test
collection = db['Student_DB']

app = Flask(__name__)
@app.route('/')
def home():
    return render_template('index.html')

@app.route('/submit', methods=['POST'])
def submit():
     form_data =dict(request.form)
     collection.insert_one(form_data)
     return 'Submitted Successfully'

@app.route('/view')
def view():
     data =collection.find()
     data= list(data)
     
     for i in data:
          print (i)
          del i['_id']    #deleted Id because we do not need the id randomly generated by the DB.

     data = {    'data':data}
     return data

if __name__ == '__main__':
     app.run(debug=True)
